services:
  central-user-manager:
    container_name: central-user-manager
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      # Overrides para entorno Docker
      SERVER_PORT: "9191"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: rahman
      DB_PASSWORD: rahman
      DB_NAME: cum
      DB_SSLMODE: disable
    ports:
      - "9191:9191"
    restart: unless-stopped
    networks:
      - shared_backend

networks:
  shared_backend:
    external: true
    name: auth-service-server_backend
