services:
  central-user-manager-client:
    container_name: central-user-manager-client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE}
    environment:
      NODE_ENV: production
      PORT: 6161
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE}
    ports:
      - '6161:6161'
    restart: unless-stopped
    # Útil si tu API corre en el host: http://host.docker.internal:5555
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # (Opcional) Healthcheck básico
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:6161/']
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  default:
    name: sso-net
    driver: bridge
