services:
  # Servicio central-user-manager
  central-user-manager:
    container_name: central-user-manager
    build:
      context: .
      dockerfile: Dockerfile

    # Cargamos todas las variables desde el archivo .env
    env_file:
      - .env

    environment:
      # Overrides para entorno Docker
      # - SERVER_PORT: lo definimos igual que en .env, pero explícito aquí por claridad
      SERVER_PORT: ${SERVER_PORT:-9191}

      # - DB_HOST: en Docker usamos el hostname del servicio postgres (no localhost)
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      DB_NAME: ${DB_NAME:-cum}
      DB_SSLMODE: ${DB_SSLMODE:-disable}

    ports:
      - "${SERVER_PORT}:${SERVER_PORT}" # expone el puerto hacia el host

    restart: unless-stopped

    networks:
      # Nos conectamos a la red ya existente que expone postgres/mongo/etc.
      - shared_backend

# Redes
networks:
  shared_backend:
    external: true
    name: auth-service-server_backend
