// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/application/application.proto

package applicationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Logo          string                 `protobuf:"bytes,5,opt,name=logo,proto3" json:"logo,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CallbackUrls  []string               `protobuf:"bytes,7,rep,name=callback_urls,json=callbackUrls,proto3" json:"callback_urls,omitempty"`
	Scopes        []string               `protobuf:"bytes,8,rep,name=scopes,proto3" json:"scopes,omitempty"`
	IsFirstParty  bool                   `protobuf:"varint,9,opt,name=is_first_party,json=isFirstParty,proto3" json:"is_first_party,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationRequest) Reset() {
	*x = CreateApplicationRequest{}
	mi := &file_proto_application_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationRequest) ProtoMessage() {}

func (x *CreateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{0}
}

func (x *CreateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApplicationRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateApplicationRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *CreateApplicationRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateApplicationRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *CreateApplicationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateApplicationRequest) GetCallbackUrls() []string {
	if x != nil {
		return x.CallbackUrls
	}
	return nil
}

func (x *CreateApplicationRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *CreateApplicationRequest) GetIsFirstParty() bool {
	if x != nil {
		return x.IsFirstParty
	}
	return false
}

type CreateApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationResponse) Reset() {
	*x = CreateApplicationResponse{}
	mi := &file_proto_application_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationResponse) ProtoMessage() {}

func (x *CreateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{1}
}

func (x *CreateApplicationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_application_application_proto protoreflect.FileDescriptor

const file_proto_application_application_proto_rawDesc = "" +
	"\n" +
	"#proto/application/application.proto\x12\vapplication\"\xa1\x02\n" +
	"\x18CreateApplicationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x12\n" +
	"\x04logo\x18\x05 \x01(\tR\x04logo\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12#\n" +
	"\rcallback_urls\x18\a \x03(\tR\fcallbackUrls\x12\x16\n" +
	"\x06scopes\x18\b \x03(\tR\x06scopes\x12$\n" +
	"\x0eis_first_party\x18\t \x01(\bR\fisFirstParty\"+\n" +
	"\x19CreateApplicationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2z\n" +
	"\x12ApplicationService\x12d\n" +
	"\x13FnCreateApplication\x12%.application.CreateApplicationRequest\x1a&.application.CreateApplicationResponseB%Z#server/pb/application;applicationpbb\x06proto3"

var (
	file_proto_application_application_proto_rawDescOnce sync.Once
	file_proto_application_application_proto_rawDescData []byte
)

func file_proto_application_application_proto_rawDescGZIP() []byte {
	file_proto_application_application_proto_rawDescOnce.Do(func() {
		file_proto_application_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_application_application_proto_rawDesc), len(file_proto_application_application_proto_rawDesc)))
	})
	return file_proto_application_application_proto_rawDescData
}

var file_proto_application_application_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_application_application_proto_goTypes = []any{
	(*CreateApplicationRequest)(nil),  // 0: application.CreateApplicationRequest
	(*CreateApplicationResponse)(nil), // 1: application.CreateApplicationResponse
}
var file_proto_application_application_proto_depIdxs = []int32{
	0, // 0: application.ApplicationService.FnCreateApplication:input_type -> application.CreateApplicationRequest
	1, // 1: application.ApplicationService.FnCreateApplication:output_type -> application.CreateApplicationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_application_application_proto_init() }
func file_proto_application_application_proto_init() {
	if File_proto_application_application_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_application_application_proto_rawDesc), len(file_proto_application_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_application_application_proto_goTypes,
		DependencyIndexes: file_proto_application_application_proto_depIdxs,
		MessageInfos:      file_proto_application_application_proto_msgTypes,
	}.Build()
	File_proto_application_application_proto = out.File
	file_proto_application_application_proto_goTypes = nil
	file_proto_application_application_proto_depIdxs = nil
}
